### ISSUE TITLE
Publish to Marketplace

### ISSUE THREAD

**Issue by silopolis** [PeterMue/vscode-linuxcnc#2]
Hi,

Would be great to have the extension published to Marketplace to complete the free machinist tools already available there :)

What's missing/left to be done ? Can we help ?

Thanks for the nice work and furthermore for sharing it with us all 🙏 

Edit: Meanwhile, some install instructions would be welcome :)

**Comment by PeterMue** [comment]
Hi,

thanks for your support.
The extension is already published at the marketplace since a while, have a look at: https://marketplace.visualstudio.com/items?itemName=PeterMue.vscode-linuxcnc

You should be able to find it when searching for "Linuxcnc".

Therefore, this should do the trick:
Launch VS Code Quick Open (Ctrl+P), paste the following command, and press enter.

```
ext install PeterMue.vscode-linuxcnc
```

Cheers, Peter
